site: cgk.sh

url: 
baseurl: 

exclude:
  - pit
  - bit
  - sit
  - Dockerfile
  - Gemfile*
  - old-shrewdraven
  - README.md
  - CLAUDE.md
  - RESUME

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  watches:
    output: true
    permalink: /horology/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "watches"
    values:
      layout: "watch"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  
